import Link from "next/link";
import { ArrowLeft, ArrowRight, ArrowUpRight, Binoculars, Check, CircleDollarSign, Clock, CloudSun, Heart, ListChecks, MapPin, Menu, Route, Search } from "lucide-react";
import { FaApple } from "react-icons/fa6";
import { BrandMark } from "./brand-mark";
import { Button } from "./ui/button";
import { APP_STORE_URL, SUPPORT_EMAIL, articles as sourceArticles, type Article } from "@/lib/site";
import { displayCurrencies, exchangeRateDate, formatNzdRange, nzdRates } from "@/lib/currency";
import { getTranslation, localizedArticles, localizedCategories, localeCodes, localeLabels, type LocaleCode } from "@/lib/localized";

const prefix = (locale: LocaleCode, path = "") => `/${locale}${path}`;

function LanguageNav({ locale }: { locale: LocaleCode }) {
  return <nav className="language-nav" aria-label="Languages"><Link href="/">English</Link>{localeCodes.map((code) => <Link href={`/${code}`} aria-current={code === locale ? "page" : undefined} key={code}>{localeLabels[code]}</Link>)}</nav>;
}

export function LocalizedHeader({ locale }: { locale: LocaleCode }) {
  const ui = getTranslation(locale).ui;
  return <header className="site-header"><div className="nav-wrap"><Link href={prefix(locale)} className="brand-link"><BrandMark/></Link><nav className="desktop-nav" aria-label="Main navigation"><Link href={`${prefix(locale)}#features`}>{ui.navFeatures}</Link><Link href={prefix(locale,"/guides")}>{ui.navGuides}</Link><Link href={prefix(locale,"/tools")}>{ui.navTools}</Link><Link href={prefix(locale,"/support")}>{ui.navSupport}</Link></nav><Button asChild size="sm" className="desktop-download"><a href={APP_STORE_URL}>{ui.download}</a></Button><details className="mobile-menu"><summary aria-label="Open menu"><Menu size={22}/></summary><nav aria-label="Mobile navigation"><Link href={`${prefix(locale)}#features`}>{ui.navFeatures}</Link><Link href={prefix(locale,"/guides")}>{ui.navGuides}</Link><Link href={prefix(locale,"/tools")}>{ui.navTools}</Link><Link href={prefix(locale,"/support")}>{ui.navSupport}</Link><a href={APP_STORE_URL}>{ui.download}</a></nav></details></div></header>;
}

export function LocalizedFooter({ locale }: { locale: LocaleCode }) {
  const ui = getTranslation(locale).ui;
  return <footer className="footer"><div className="footer-grid"><div><BrandMark/><p>{ui.footerText}</p></div><div><strong>{ui.explore}</strong><Link href={prefix(locale,"/guides")}>{ui.travelGuides}</Link><Link href={prefix(locale,"/tools")}>{ui.navTools}</Link><Link href={`${prefix(locale)}#features`}>{ui.navFeatures}</Link></div><div><strong>{ui.help}</strong><Link href={prefix(locale,"/support")}>{ui.navSupport}</Link><a href={`mailto:${SUPPORT_EMAIL}`}>{ui.contact}</a><a href="https://github.com/CristianRus4/kiwicamping-web/tree/main/docs">{ui.photoCredits}</a></div><div><strong>{ui.getApp}</strong><a href={APP_STORE_URL}>{ui.download}</a><Link href={prefix(locale,"/privacy")}>{ui.privacy}</Link><Link href={prefix(locale,"/terms")}>{ui.terms}</Link></div></div><LanguageNav locale={locale}/><div className="footer-bottom"><span>© {new Date().getFullYear()} KiwiCamping</span><span>{ui.footerLine}</span></div></footer>;
}

function StoreLink({ locale }: { locale: LocaleCode }) { const ui=getTranslation(locale).ui; return <a className="store-button" href={APP_STORE_URL}><FaApple aria-hidden="true"/><span>{ui.download}</span></a>; }

function LocalizedCard({ article, locale }: { article: Article; locale: LocaleCode }) {
  const ui=getTranslation(locale).ui;
  return <Link className="article-card" href={prefix(locale,`/guides/${article.slug}`)}><div className="article-image" style={{backgroundImage:`linear-gradient(180deg, transparent 35%, rgba(16,26,13,.45)), url(${article.image})`}}><span>{article.category}</span></div><div className="article-card-copy"><div className="eyebrow"><MapPin size={13}/>{article.region} · {article.readTime} min</div><h3>{article.title}</h3><p>{article.description}</p><span className="text-link">{ui.readGuide} <ArrowUpRight size={15}/></span></div></Link>;
}

export function LocalizedHome({ locale }: { locale: LocaleCode }) {
  const ui=getTranslation(locale).ui; const articleList=localizedArticles(locale);
  const features=[[Heart,ui.feature1Title,ui.feature1Text],[Route,ui.feature2Title,ui.feature2Text],[ListChecks,ui.feature3Title,ui.feature3Text],[CircleDollarSign,ui.feature4Title,ui.feature4Text],[CloudSun,ui.feature5Title,ui.feature5Text],[Binoculars,ui.feature6Title,ui.feature6Text]] as const;
  const reviews=[["Sofia M.",ui.review1Country,ui.review1Title,ui.review1Quote],["Daniel R.",ui.review2Country,ui.review2Title,ui.review2Quote],["Claire T.",ui.review3Country,ui.review3Title,ui.review3Quote],["Matteo B.",ui.review4Country,ui.review4Title,ui.review4Quote],["Emma L.",ui.review5Country,ui.review5Title,ui.review5Quote]];
  const faqs=[[ui.faq1q,ui.faq1a],[ui.faq2q,ui.faq2a],[ui.faq3q,ui.faq3a],[ui.faq4q,ui.faq4a]];
  return <><LocalizedHeader locale={locale}/><main><section className="hero"><div className="hero-grid"><div className="hero-copy"><span className="kicker">{ui.heroKicker}</span><h1>{ui.heroTitle}</h1><p>{ui.heroText}</p><div className="hero-actions"><div className="download-card"><div className="qr-image" style={{backgroundImage:"url(/images/kiwicamping-qr.png)"}}/><StoreLink locale={locale}/></div><Button asChild variant="outline" size="lg"><Link href={`${prefix(locale)}#features`}>{ui.seeHow}<ArrowRight/></Link></Button></div><div className="hero-proof"><span><strong>4,500+</strong><small>{ui.placesCount.replace("4,500+ ","")}</small></span><span><strong>2,000+</strong><small>{ui.staysCount.replace("2,000+ ","")}</small></span><span><strong>Offline</strong><small>{ui.offline.replace(/^Offline\s*/i,"")}</small></span></div></div><div className="hero-visual"><div className="image-slot hero-image-slot" style={{backgroundImage:"url(/images/kiwicamping-hero.webp)"}}/></div></div></section>
  <section className="section story-section"><div className="section-head"><div><p className="eyebrow">{ui.processEyebrow}</p><h2>{ui.processTitle}</h2></div><p>{ui.processText}</p></div><div className="steps-grid">{[[Search,ui.findTitle,ui.findText],[Heart,ui.saveTitle,ui.saveText],[Route,ui.planTitle,ui.planText]].map(([Icon,title,text])=><article key={String(title)}><Icon/><h3>{String(title)}</h3><p>{String(text)}</p></article>)}</div></section>
  <section className="feature-stage" id="features"><div className="feature-intro"><p className="eyebrow">{ui.featuresEyebrow}</p><h2>{ui.featuresTitle}</h2><p>{ui.featuresText}</p></div><div className="feature-showcase"><div className="feature-copy-large"><p className="eyebrow">KiwiCamping</p><h3>{ui.featureMainTitle}</h3><p>{ui.featureMainText}</p><ul><li><Check/>{ui.featureList1}</li><li><Check/>{ui.featureList2}</li><li><Check/>{ui.featureList3}</li></ul></div><div className="product-images"><div className="image-slot product-shot product-shot-one" style={{backgroundImage:"url(/images/kiwicamping-feature-1.webp)"}}/><div className="image-slot product-shot product-shot-two" style={{backgroundImage:"url(/images/kiwicamping-feature-2.webp)"}}/></div></div><div className="feature-grid">{features.map(([Icon,title,text])=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="section itinerary-section"><div className="itinerary-image image-slot" style={{backgroundImage:"url(/images/kiwicamping-feature-3.webp)"}}/><div className="itinerary-copy"><p className="eyebrow">KiwiCamping</p><h2>{ui.plannerTitle}</h2><p>{ui.plannerText}</p></div></section>
  <section className="section guide-preview"><div className="guide-preview-head"><div><p className="eyebrow">{ui.routesEyebrow}</p><h2>{ui.routesTitle}</h2></div><div><p>{ui.routesText}</p><Link href={prefix(locale,"/guides")} className="text-link">{ui.exploreRoutes}<ArrowRight/></Link></div></div><div className="article-grid">{articleList.slice(0,3).map((article)=><LocalizedCard article={article} locale={locale} key={article.slug}/>)}</div></section>
  <section className="reviews-section"><div className="reviews-head"><div><p className="eyebrow">{ui.reviewsEyebrow}</p><h2>{ui.reviewsTitle}</h2></div></div><div className="review-wall">{reviews.map(([name,country,title,quote],index)=><article className={`review-card review-${index+1}`} key={name}><div className="review-stars">★★★★★</div><h3>{title}</h3><blockquote>“{quote}”</blockquote><footer><span className="review-avatar">{name[0]}</span><span><strong>{name}</strong><small>{country}</small></span></footer></article>)}</div></section>
  <section className="section faq-section"><div><h2>{ui.faqTitle}</h2><p>{ui.faqIntro}</p></div><div className="faq-list">{faqs.map(([question,answer],index)=><details key={question} open={index===0}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
  <section className="download-section"><div className="download-image image-slot" style={{backgroundImage:"url(/images/kiwicamping-feature-6.webp)"}}/><div className="download-copy"><h2>{ui.downloadTitle}</h2><p>{ui.downloadText}</p><StoreLink locale={locale}/></div></section></main><Button asChild className="mobile-cta"><a href={APP_STORE_URL}><FaApple aria-hidden="true"/><span>{ui.download}</span></a></Button><LocalizedFooter locale={locale}/></>;
}

export function LocalizedGuides({ locale }: { locale: LocaleCode }) { const ui=getTranslation(locale).ui; const list=localizedArticles(locale); return <><LocalizedHeader locale={locale}/><main><section className="page-hero guides-hero"><p className="eyebrow">{ui.guidesEyebrow}</p><h1>{ui.guidesTitle}</h1><p>{list.length} {ui.guidesIntro}</p></section><section className="content-shell">{localizedCategories(locale).map(({source,label})=>{const group=list.filter((_,index)=>sourceArticles[index].category===source);return <section className="category-section" key={source}><div className="category-heading"><h2>{label}</h2><span>{group.length} {group.length===1?ui.guideSingular:ui.guidePlural}</span></div><div className="article-grid">{group.map((article)=><LocalizedCard article={article} locale={locale} key={article.slug}/>)}</div></section>;})}</section></main><LocalizedFooter locale={locale}/></>; }

export function LocalizedArticle({ locale, slug }: { locale: LocaleCode; slug: string }) {
  const ui=getTranslation(locale).ui; const list=localizedArticles(locale); const item=list.find((article)=>article.slug===slug); if(!item)return null;
  const related=list.filter((article)=>article.slug!==slug&&(article.category===item.category||article.region===item.region)).slice(0,3);
  return <><LocalizedHeader locale={locale}/><main><article className="article-page"><div className="article-breadcrumb"><Link href={prefix(locale,"/guides")}><ArrowLeft/>{ui.backToGuides}</Link><span>{item.category}</span></div><header className="article-header"><p className="eyebrow">{item.category} · {item.region}</p><h1>{item.title}</h1><p>{item.description}</p><div><span><Clock/>{item.readTime} {ui.minuteRead}</span><span><MapPin/>{item.places.length} {ui.places}</span></div></header><figure className="article-hero-image" style={{backgroundImage:`url(${item.image})`}} aria-label={item.imageAlt}><figcaption className="article-photo-credit"><a href="https://github.com/CristianRus4/kiwicamping-web/tree/main/docs">{ui.photoCredits}</a></figcaption></figure><div className="article-layout"><div className="article-body"><p className="article-intro">{item.intro}</p>
  {item.priceTable&&<section className="article-price-section"><span className="section-count">NZD</span><h2>{ui.priceTitle}</h2><p>{item.priceTable.note}</p><div className="price-table-meta"><strong>{ui.pricesChecked} {item.priceTable.asOf}</strong><span>{ui.conversionsUse} {exchangeRateDate}.</span></div><div className="price-table-wrap"><table className="price-table"><thead><tr><th>{ui.item}</th>{displayCurrencies.map((currency)=><th key={currency}>{currency}</th>)}</tr></thead><tbody>{item.priceTable.rows.map((row)=><tr key={row.label}><th><strong>{row.label}</strong>{row.unit&&<span>{row.unit}</span>}</th>{displayCurrencies.map((currency)=><td key={currency}>{formatNzdRange(row.nzdLow,row.nzdHigh,currency)}</td>)}</tr>)}</tbody></table></div><p className="price-table-disclaimer">{ui.currencyDisclaimer}</p></section>}
  {item.sections.map((section,index)=><section key={section.heading}><span className="section-count">{String(index+1).padStart(2,"0")}</span><h2>{section.heading}</h2>{section.body.map((paragraph:string)=><p key={paragraph}>{paragraph}</p>)}{section.tips&&<div className="article-tips"><strong>{ui.keepInMind}</strong><ul>{section.tips.map((tip)=><li key={tip}>{tip}</li>)}</ul></div>}</section>)}<section><span className="section-count">MAP</span><h2>{ui.placesAlong}</h2><div className="place-chips">{item.places.map((place)=><span key={place}><MapPin/>{place}</span>)}</div></section>{item.sources&&<section className="sources"><h2>{ui.checkBefore}</h2><p>{ui.checkText}</p><ul>{item.sources.map((source)=><li key={source.url}><a href={source.url}>{source.label}<ArrowRight/></a></li>)}</ul></section>}<div className="article-end-cta"><div><p className="eyebrow">{ui.takeRoad}</p><h2>{ui.savePlanTitle}</h2><p>{ui.savePlanText}</p></div><StoreLink locale={locale}/></div></div></div></article><section className="related-section"><h2>{ui.related}</h2><div className="article-grid">{related.map((article)=><LocalizedCard article={article} locale={locale} key={article.slug}/>)}</div></section></main><LocalizedFooter locale={locale}/></>;
}

export function LocalizedTools({locale}:{locale:LocaleCode}) { const ui=getTranslation(locale).ui; const script=`(function(){const rates=${JSON.stringify(nzdRates)};const money=(v,c)=>new Intl.NumberFormat('${locale}',{style:'currency',currency:c,maximumFractionDigits:c==='JPY'||c==='KRW'?0:v<10?2:0}).format(v);const c=document.querySelector('[data-currency-tool]');const uc=()=>{const a=Number(c.querySelector('[data-currency-amount]').value),f=c.querySelector('[data-currency-from]').value,t=c.querySelector('[data-currency-to]').value;c.querySelector('[data-currency-output]').textContent=money(a/rates[f]*rates[t],t)};c.addEventListener('input',uc);const x=document.querySelector('[data-fuel-tool]');const uf=()=>{const d=Number(x.querySelector('[data-fuel-distance]').value),u=Number(x.querySelector('[data-fuel-consumption]').value),p=Number(x.querySelector('[data-fuel-price]').value),l=d*u/100;x.querySelector('[data-fuel-output]').textContent=l.toFixed(1)+' L · NZ$'+(l*p).toFixed(2)};x.addEventListener('input',uf)})();`; return <><LocalizedHeader locale={locale}/><main><section className="page-hero tools-hero"><p className="eyebrow">{ui.toolsEyebrow}</p><h1>{ui.toolsTitle}</h1><p>{ui.toolsIntro}</p></section><section className="tools-shell"><section className="tool-card" data-currency-tool><h2>{ui.currencyTitle}</h2><p>{ui.conversionsUse} {exchangeRateDate}.</p><div className="converter-grid"><label><span>{ui.amount}</span><input data-currency-amount defaultValue="100"/></label><label><span>{ui.from}</span><select data-currency-from defaultValue="NZD">{displayCurrencies.map(c=><option key={c}>{c}</option>)}</select></label><label><span>{ui.to}</span><select data-currency-to defaultValue="USD">{displayCurrencies.map(c=><option key={c}>{c}</option>)}</select></label></div><output className="tool-output" data-currency-output>US$58.72</output></section><section className="tool-card" data-fuel-tool><h2>{ui.fuelTitle}</h2><div className="converter-grid"><label><span>{ui.distance} (km)</span><input data-fuel-distance defaultValue="1000"/></label><label><span>{ui.fuelUse} (L/100 km)</span><input data-fuel-consumption defaultValue="12"/></label><label><span>{ui.fuelPrice} (NZD/L)</span><input data-fuel-price defaultValue="2.96"/></label></div><output className="tool-output" data-fuel-output>120.0 L · NZ$355.20</output></section><section className="tools-note"><p>{ui.calculatorNote}</p></section></section></main><LocalizedFooter locale={locale}/><script data-static-tools dangerouslySetInnerHTML={{__html:script}}/></>; }

type InformationPage={effective?:string;title:string;lede:string;sections:Array<{heading:string;paragraphs:string[]}>};
export function LocalizedInformationPage({locale,kind}:{locale:LocaleCode;kind:"support"|"privacy"|"terms"}) { const translation=getTranslation(locale) as unknown as {ui:ReturnType<typeof getTranslation>["ui"];pages:Record<"support"|"privacy"|"terms",InformationPage>}; const ui=translation.ui; const page=translation.pages?.[kind]; if(!page)return null; return <><LocalizedHeader locale={locale}/><main className={kind==="support"?undefined:"legal-page"}>{kind==="support"?<section className="page-hero support-hero"><p className="eyebrow">{ui.navSupport}</p><h1>{page.title}</h1><p>{page.lede}</p><Button asChild size="lg"><a href={`mailto:${SUPPORT_EMAIL}`}>{ui.contact}</a></Button></section>:<><p className="eyebrow">{page.effective}</p><h1>{page.title}</h1><p className="legal-lede">{page.lede}</p></>}<section className={kind==="support"?"support-shell":undefined}>{page.sections.map((section)=><section className={kind==="support"?"support-group":undefined} key={section.heading}><div><h2>{section.heading}</h2></div><div>{section.paragraphs.map((paragraph)=><p key={paragraph}>{paragraph}</p>)}</div></section>)}</section></main><LocalizedFooter locale={locale}/></>; }
