import manifest from "@/lib/image-manifest.json";

type ManifestEntry = { width: number; height: number; variants: { path: string; width: number }[] };
const images = manifest as Record<string, ManifestEntry>;

/* eslint-disable @next/next/no-img-element -- The site is a static export with no image
   optimisation server, so `next/image` has nothing to optimise with; these are hand-sized
   `<img>` elements with a pre-generated srcset, which is the same result without the runtime. */

/**
 * Every image on the site is a real `<img>`, never a CSS background.
 *
 * Backgrounds were invisible to Google Images, carried no `alt`, could not be preloaded and could
 * not serve a smaller file to a phone. These two components keep the old geometry (the slots still
 * size and position exactly as the `background-size` rules did) while giving each image intrinsic
 * dimensions, a `srcset` and real alt text.
 *
 * Sizes come from `lib/image-manifest.json`, generated by `npm run images:manifest`.
 */
function sourceAttributes(src: string, priority: boolean) {
  const entry = images[src];
  if (!entry) throw new Error(`No image-manifest entry for "${src}". Run \`npm run images:manifest\`.`);
  return {
    src,
    srcSet: entry.variants.map((variant) => `${variant.path} ${variant.width}w`).join(", "),
    width: entry.width,
    height: entry.height,
    // The one above-the-fold image per page loads eagerly at high priority; everything else waits
    // until it is near the viewport.
    loading: priority ? ("eager" as const) : ("lazy" as const),
    fetchPriority: priority ? ("high" as const) : undefined,
    decoding: priority ? ("sync" as const) : ("async" as const),
  };
}

type ImageProps = { src: string; alt: string; sizes: string; priority?: boolean; className?: string };

/** A device screenshot, centred inside its slot at 90% of the slot height, as the old CSS did. */
export function ScreenshotImage({ src, alt, sizes, priority = false, className = "" }: ImageProps) {
  return (
    <div className={`image-slot ${className}`.trim()}>
      <img alt={alt} sizes={sizes} {...sourceAttributes(src, priority)} />
    </div>
  );
}

/** A photo that fills and crops to its container, as `background-size: cover` did. */
export function CoverImage({ src, alt, sizes, priority = false, className = "" }: ImageProps) {
  return <img className={`cover-image ${className}`.trim()} alt={alt} sizes={sizes} {...sourceAttributes(src, priority)} />;
}
