import dates from "@/lib/article-dates.json";

/**
 * When each guide was first published and last rewritten, from git history.
 *
 * Generated by `npm run articles:dates`; see that script for why the dates are read from commits
 * rather than typed in. A guide with no entry yet (one added but not committed) simply has no date,
 * and the page omits it rather than showing a guess.
 */
const table = dates as Record<string, { published: string; modified: string }>;

export const articleDates = (slug: string) => table[slug];

/** "18 August 2026", the form the article header shows. */
export function formatArticleDate(iso: string): string {
  return new Date(`${iso}T00:00:00Z`).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" });
}
