import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { SUPPORT_EMAIL } from "@/lib/site";
import { seoLanguageTags } from "@/lib/seo";
import { BookOpen, Mail, MapPinned, Route, Search, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata:Metadata={title:"Support and FAQ",description:"Help with KiwiCamping maps, place details, filters, collections, the trip planner, offline data, currency conversion and premium access.",alternates:{canonical:"/support",languages:seoLanguageTags("/support")}};
const groups=[{icon:Search,title:"Finding places",items:[["How do I search?","Use Explore to search by place name, address or description. Move the map and choose the current-area option to focus results around the visible region."],["How do filters work?","Filter by place category, fee, booking and detailed feature groups. Combine only the filters that matter so useful alternatives remain visible."],["Why can a place differ from its listing?","Facilities, fees, access and management can change. Follow current signs and the land manager, then send a correction so the directory can improve."]]},{icon:MapPinned,title:"Saved places",items:[["What are smart collections?","Liked, Visited, Want to Visit and Starred update automatically when you mark places. Pins and All Saved provide other quick views."],["Can I make my own collection?","Yes. Create named collections with an icon and notes, then add any place. Use them for a region, season, vehicle or shortlist."],["Does saved data sync?","The app supports private iCloud sync for saved states, collections and trip data when iCloud is available and enabled."]]},{icon:Route,title:"Trip planner",items:[["How do I add stops?","Create a trip, add places and reorder them. You can attach arrival dates, notes and visited status to individual stops."],["What happens if a route cannot be calculated?","Road routing depends on available MapKit directions. The planner retains the stops and can fall back for a failed leg, but you must confirm current road access yourself."],["Can I add a packing list?","Yes. Start with a camping essentials preset or make your own tasks. Trip progress keeps the list beside the itinerary."]]},{icon:BookOpen,title:"Guides and live details",items:[["Can I book a place from a route?","Open a place to find its booking or contact details, then check availability, price and terms with the provider."],["Does weather work offline?","Current and forecast weather requires live data. Save critical forecasts and official warnings before leaving coverage."],["Which details are offline?","The bundled place directory keeps core place details available beyond reliable signal. Live maps, routing, weather and external provider pages may require reception."]]},{icon:ShieldCheck,title:"Premium and account",items:[["What is included for free?","Map and place details are free, together with two saved lists."],["What does Premium add?","Premium adds unlimited saved lists, trip planning, advanced filters, place weather and road trip routes."],["How do I restore a purchase?","Open the Premium screen and use Restore Purchases while signed into the Apple account used for the original transaction."]]}];
export default function Support(){return <><Header/><main><section className="page-hero support-hero"><p className="eyebrow">Support</p><h1>How can we<br/><em>help?</em></h1><p>Clear answers for maps, saved places, trip planning and the road ahead.</p><Button asChild size="lg"><a href={`mailto:${SUPPORT_EMAIL}`}><Mail/>Email support</a></Button></section><section className="support-shell">{groups.map(({icon:Icon,title,items})=><section className="support-group" key={title}><div><Icon/><h2>{title}</h2></div><div>{items.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>)}<section className="contact-panel"><Mail/><div><p className="eyebrow">Still need a hand?</p><h2>Tell us what happened.</h2><p>Include the app version, your device, the place or trip involved and what you expected to see. Please do not send payment details.</p></div><Button asChild variant="light"><a href={`mailto:${SUPPORT_EMAIL}?subject=KiwiCamping%20support`}>Contact support</a></Button></section><p className="legal-links">Looking for the small print? Read our <Link href="/privacy">privacy policy</Link> and <Link href="/terms">terms</Link>.</p></section></main><Footer/></>}
